syntax on
filetype plugin indent on
set expandtab
set smarttab
set tabstop=4
set shiftwidth=4
set softtabstop=4

set nu 				"line numbers on (set nonu)

" change directory to files current directory
autocmd BufEnter * silent! lcd %:p:h
